### ISSUE TITLE
buttons on case-light-round-1.6mm-pcb-printed-straps

### ISSUE THREAD

**Issue by targor** [Open-Smartwatch/3d-files#4]
Are there any printable buttons for case-light-round-1.6mm-pcb-printed-straps? Or do i get something wrong here?

**Comment by uvwxy** [comment]
I added all the missing button files, in your example: 

https://github.com/Open-Smartwatch/3d-files/blob/master/case-light-round-1.6mm-pcb-printed-straps/case-light-round-1.6mm-pcb-printed-straps-buttons-pla.stl

**Comment by targor** [comment]
thank you so much :)  👍 .
